#!/bin/bash
# Display help information for REM RAG query scripts

echo "=================================================================================="
echo "                          REM RAG Query Scripts Help"
echo "=================================================================================="
echo ""
echo "This directory contains scripts for querying and exploring the REM RAG knowledge base."
echo ""
echo "AVAILABLE SCRIPTS:"
echo ""
echo "1. ask.sh - Ask questions to the REM RAG system"
echo "   Usage: ./ask.sh [options] \"Your question\""
echo "   "
echo "   Options:"
echo "     -i, --interactive     Run in interactive mode (multiple questions)"
echo "     -s, --show-sources    Show source passages used for the answer"
echo "     --k NUMBER           Number of context passages to retrieve (default: 10)"
echo "     --no-chunks          Don't display retrieved chunks (only show response)"
echo "   "
echo "   Examples:"
echo "     ./ask.sh \"What patterns emerged about sovereignty?\""
echo "     ./ask.sh --show-sources \"How has nuclear deterrence evolved?\""
echo "     ./ask.sh --interactive"
echo "     ./ask.sh --k 20 --no-chunks \"What role does technology play in diplomacy?\""
echo ""
echo "2. query_random.sh - Query random nodes from the database"
echo "   Usage: ./query_random.sh [options]"
echo "   "
echo "   Options:"
echo "     --node-type TYPE     Filter by node type (chunk, synthesis, learning, rem)"
echo "     --neighbors          Also retrieve 5 nearest neighbors"
echo "     --count              Only return counts, not content"
echo "     --num-samples N      Number of random nodes to sample (default: 1)"
echo "   "
echo "   Examples:"
echo "     ./query_random.sh --count                     # Show counts of all node types"
echo "     ./query_random.sh --node-type rem --neighbors # Get a REM node with neighbors"
echo "     ./query_random.sh --node-type synthesis --num-samples 3"
echo ""
echo "3. query_examples.sh - Show example commands"
echo "   Usage: ./query_examples.sh"
echo "   "
echo "   Displays various example queries demonstrating system capabilities."
echo ""
echo "4. help.sh - This help message"
echo "   Usage: ./help.sh"
echo ""
echo "=================================================================================="
echo "UNDERSTANDING NODE TYPES:"
echo ""
echo "  - chunk:     Original text segments from articles"
echo "  - synthesis: Comparisons with existing knowledge"
echo "  - learning:  Entity-specific insights"
echo "  - rem:       Patterns discovered during REM cycles"
echo "  - summary:   Article-level summaries"
echo ""
echo "=================================================================================="
echo "TIPS:"
echo ""
echo "1. Start with interactive mode to explore: ./ask.sh --interactive"
echo "2. Use --show-sources to see which passages informed the answer"
echo "3. Check node counts first: ./query_random.sh --count"
echo "4. Explore REM insights: ./query_random.sh --node-type rem --neighbors"
echo "5. The system compares raw GPT responses with RAG-enhanced responses"
echo ""
echo "=================================================================================="